// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7cvdD9xsT1bDUevx31TX5ALXcC_r8GY',
    appId: '1:1029582835304:web:44112534313bc9657a75dd',
    messagingSenderId: '1029582835304',
    projectId: 'expanse-tracker-172f0',
    authDomain: 'expanse-tracker-172f0.firebaseapp.com',
    storageBucket: 'expanse-tracker-172f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrGs2diuW5k-te-Nxu9tqeUCuIfr1RYA',
    appId: '1:1029582835304:android:965a7850e3b200b87a75dd',
    messagingSenderId: '1029582835304',
    projectId: 'expanse-tracker-172f0',
    storageBucket: 'expanse-tracker-172f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZISS-C1ro919tkMjZ9d0WMsHPsKffDyQ',
    appId: '1:1029582835304:ios:67ce4431384d22997a75dd',
    messagingSenderId: '1029582835304',
    projectId: 'expanse-tracker-172f0',
    storageBucket: 'expanse-tracker-172f0.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZISS-C1ro919tkMjZ9d0WMsHPsKffDyQ',
    appId: '1:1029582835304:ios:a43345d6082637bd7a75dd',
    messagingSenderId: '1029582835304',
    projectId: 'expanse-tracker-172f0',
    storageBucket: 'expanse-tracker-172f0.appspot.com',
    iosBundleId: 'com.example.expensetracker.RunnerTests',
  );
}
