name: expanse_repository
description: A repo to handle expanses.

publish_to: 'none'



environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  firebase_auth:  ^4.16.0
  cloud_firestore:  ^4.15.9






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

